<template lang="">
  <div class="text-white">
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur elementum et libero sed ultricies. Sed eleifend justo porta, semper tellus at, sagittis ante. Integer placerat massa eu enim vulputate mollis. Vestibulum non lacus ac lectus congue pellentesque in sed leo. Nunc id mi in quam ultricies rhoncus sit amet eget nunc. Phasellus at metus ac tellus vulputate auctor sit amet cursus augue. Duis porta magna ac elit sodales fermentum. Nullam suscipit, ipsum at imperdiet ornare, neque orci tempor eros, imperdiet egestas risus diam sit amet nulla. Donec quis feugiat augue. Aenean tincidunt, nibh id vestibulum aliquet, felis massa euismod ligula, quis volutpat neque turpis ac sapien. Nam in blandit ante. Morbi id justo vitae justo placerat rutrum ac in velit.
  Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed mattis pretium quam, a sagittis velit ornare a. Etiam vel volutpat mi. Phasellus vitae malesuada ex. Mauris vulputate felis ut leo placerat, a cursus nisl tincidunt. Ut vitae suscipit velit. Pellentesque ullamcorper fringilla leo id posuere. Proin ullamcorper libero at eros lobortis, sodales molestie ligula suscipit. Proin vel feugiat mauris. Nullam ut ultrices nibh. Mauris felis nisl, efficitur sit amet lorem at, venenatis varius dolor. Duis congue congue ipsum, in sollicitudin tellus sagittis sit amet.
  Cras quis sapien eu ex facilisis venenatis. In maximus libero lacus, id suscipit turpis facilisis eu. Suspendisse non metus in nisi hendrerit fringilla. Ut sapien diam, pharetra ac porttitor sit amet, viverra nec turpis. Cras sodales gravida vestibulum. Donec id lacus maximus, pulvinar ante et, tempus odio. Ut nec semper urna. Suspendisse dignissim consequat lacus, placerat commodo enim condimentum quis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Maecenas id efficitur nisi, sit amet commodo diam.
  Etiam pretium feugiat tincidunt. Nunc scelerisque, est id rutrum malesuada, velit magna porttitor nibh, ut condimentum augue erat nec felis. Praesent in mattis magna, a scelerisque augue. In ultrices convallis libero et venenatis. Nullam lobortis bibendum sem quis suscipit. Fusce commodo mi eros, nec scelerisque nibh placerat vitae. Suspendisse sed lacus et nibh feugiat ultricies at ut arcu.
  Nam congue odio id mi sagittis, ac tincidunt mauris efficitur. Cras gravida tortor nec posuere condimentum. In ex tellus, mattis ut turpis quis, malesuada tempus mauris. Proin ut tincidunt odio, non pellentesque libero. Suspendisse potenti. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Quisque venenatis mi et scelerisque tempor. Aliquam tempor lectus ut magna viverra, eu dignissim libero hendrerit. Aliquam nec purus ligula. Integer a est congue, ultrices nisl vestibulum, finibus mi. Ut magna leo, pellentesque et ipsum sit amet, vulputate molestie augue.
  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur elementum et libero sed ultricies. Sed eleifend justo porta, semper tellus at, sagittis ante. Integer placerat massa eu enim vulputate mollis. Vestibulum non lacus ac lectus congue pellentesque in sed leo. Nunc id mi in quam ultricies rhoncus sit amet eget nunc. Phasellus at metus ac tellus vulputate auctor sit amet cursus augue. Duis porta magna ac elit sodales fermentum. Nullam suscipit, ipsum at imperdiet ornare, neque orci tempor eros, imperdiet egestas risus diam sit amet nulla. Donec quis feugiat augue. Aenean tincidunt, nibh id vestibulum aliquet, felis massa euismod ligula, quis volutpat neque turpis ac sapien. Nam in blandit ante. Morbi id justo vitae justo placerat rutrum ac in velit.
  Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed mattis pretium quam, a sagittis velit ornare a. Etiam vel volutpat mi. Phasellus vitae malesuada ex. Mauris vulputate felis ut leo placerat, a cursus nisl tincidunt. Ut vitae suscipit velit. Pellentesque ullamcorper fringilla leo id posuere. Proin ullamcorper libero at eros lobortis, sodales molestie ligula suscipit. Proin vel feugiat mauris. Nullam ut ultrices nibh. Mauris felis nisl, efficitur sit amet lorem at, venenatis varius dolor. Duis congue congue ipsum, in sollicitudin tellus sagittis sit amet.
  Cras quis sapien eu ex facilisis venenatis. In maximus libero lacus, id suscipit turpis facilisis eu. Suspendisse non metus in nisi hendrerit fringilla. Ut sapien diam, pharetra ac porttitor sit amet, viverra nec turpis. Cras sodales gravida vestibulum. Donec id lacus maximus, pulvinar ante et, tempus odio. Ut nec semper urna. Suspendisse dignissim consequat lacus, placerat commodo enim condimentum quis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Maecenas id efficitur nisi, sit amet commodo diam.
  Etiam pretium feugiat tincidunt. Nunc scelerisque, est id rutrum malesuada, velit magna porttitor nibh, ut condimentum augue erat nec felis. Praesent in mattis magna, a scelerisque augue. In ultrices convallis libero et venenatis. Nullam lobortis bibendum sem quis suscipit. Fusce commodo mi eros, nec scelerisque nibh placerat vitae. Suspendisse sed lacus et nibh feugiat ultricies at ut arcu.
  Nam congue odio id mi sagittis, ac tincidunt mauris efficitur. Cras gravida tortor nec posuere condimentum. In ex tellus, mattis ut turpis quis, malesuada tempus mauris. Proin ut tincidunt odio, non pellentesque libero. Suspendisse potenti. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Quisque venenatis mi et scelerisque tempor. Aliquam tempor lectus ut magna viverra, eu dignissim libero hendrerit. Aliquam nec purus ligula. Integer a est congue, ultrices nisl vestibulum, finibus mi. Ut magna leo, pellentesque et ipsum sit amet, vulputate molestie augue.
  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur elementum et libero sed ultricies. Sed eleifend justo porta, semper tellus at, sagittis ante. Integer placerat massa eu enim vulputate mollis. Vestibulum non lacus ac lectus congue pellentesque in sed leo. Nunc id mi in quam ultricies rhoncus sit amet eget nunc. Phasellus at metus ac tellus vulputate auctor sit amet cursus augue. Duis porta magna ac elit sodales fermentum. Nullam suscipit, ipsum at imperdiet ornare, neque orci tempor eros, imperdiet egestas risus diam sit amet nulla. Donec quis feugiat augue. Aenean tincidunt, nibh id vestibulum aliquet, felis massa euismod ligula, quis volutpat neque turpis ac sapien. Nam in blandit ante. Morbi id justo vitae justo placerat rutrum ac in velit.
  Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed mattis pretium quam, a sagittis velit ornare a. Etiam vel volutpat mi. Phasellus vitae malesuada ex. Mauris vulputate felis ut leo placerat, a cursus nisl tincidunt. Ut vitae suscipit velit. Pellentesque ullamcorper fringilla leo id posuere. Proin ullamcorper libero at eros lobortis, sodales molestie ligula suscipit. Proin vel feugiat mauris. Nullam ut ultrices nibh. Mauris felis nisl, efficitur sit amet lorem at, venenatis varius dolor. Duis congue congue ipsum, in sollicitudin tellus sagittis sit amet.
  Cras quis sapien eu ex facilisis venenatis. In maximus libero lacus, id suscipit turpis facilisis eu. Suspendisse non metus in nisi hendrerit fringilla. Ut sapien diam, pharetra ac porttitor sit amet, viverra nec turpis. Cras sodales gravida vestibulum. Donec id lacus maximus, pulvinar ante et, tempus odio. Ut nec semper urna. Suspendisse dignissim consequat lacus, placerat commodo enim condimentum quis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Maecenas id efficitur nisi, sit amet commodo diam.
  Etiam pretium feugiat tincidunt. Nunc scelerisque, est id rutrum malesuada, velit magna porttitor nibh, ut condimentum augue erat nec felis. Praesent in mattis magna, a scelerisque augue. In ultrices convallis libero et venenatis. Nullam lobortis bibendum sem quis suscipit. Fusce commodo mi eros, nec scelerisque nibh placerat vitae. Suspendisse sed lacus et nibh feugiat ultricies at ut arcu.
  Nam congue odio id mi sagittis, ac tincidunt mauris efficitur. Cras gravida tortor nec posuere condimentum. In ex tellus, mattis ut turpis quis, malesuada tempus mauris. Proin ut tincidunt odio, non pellentesque libero. Suspendisse potenti. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Quisque venenatis mi et scelerisque tempor. Aliquam tempor lectus ut magna viverra, eu dignissim libero hendrerit. Aliquam nec purus ligula. Integer a est congue, ultrices nisl vestibulum, finibus mi. Ut magna leo, pellentesque et ipsum sit amet, vulputate molestie augue.
  </div>
</template>

<script setup>
definePageMeta({
  layout: 'client-sidebar'
})

const loading = ref(false)
</script>